/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface LastViewed {
  iid: string | null;
  last_viewed: string | null;
}

export interface ShowBookmark {
  favourite: Generated<number>;
  iid: string | null;
  note: string | null;
}

export interface ShowBookmarkOld {
  favourite: number | null;
  iid: string | null;
  note: string | null;
}

export interface DB {
  last_viewed: LastViewed;
  show_bookmark: ShowBookmark;
  show_bookmark_old: ShowBookmarkOld;
}
